# Online Swagger formatter: https://editor.swagger.io/

/product/all:
  get:
    summary: Get All Products
    parameters:
      - in: query
        name: userId
        schema:
          type: string
    tags:
      - Product
    responses:
      200:
        description: Successfully
      400:
        description: Failed

/product:
  get:
    summary: Get Product
    parameters:
      - in: query
        name: userId
        schema:
          type: string
      - in: query
        name: productId
        schema:
          type: string
    tags:
      - Product
    responses:
      200:
        description: Successfully
      400:
        description: Failed

/product/cultivate:
  post:
    summary: Cultivate Product
    tags:
      - Product
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              userId:
                type: string
                required: true
              productObj:
                type: object
                required: true
            example:
              userId: "g53a0000-8669-4a07-a23a-d18055600000"
              productObj:
                {
                  ProductId: "Product1",
                  ProductName: "Gạo tẻ",
                  Dates:
                    {
                      Cultivated: "",
                      Harvested: "",
                      Imported: "",
                      Manufacturered: "",
                      Exported: "",
                      Distributed: "",
                      Sold: ""
                    },
                  Actors:
                    {
                      SupplierId: "",
                      ManufacturerId: "",
                      DistributorId: "",
                      RetailerId: ""
                    },
                  Price: "100000",
                  Status: "",
                  Description: "Gạo tẻ đạt chuẩn"
                }
    responses:
      200:
        description: Successfully
      400:
        description: Failed

/product/harvert:
  post:
    summary: Harvert Product
    tags:
      - Product
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              userId:
                type: string
                required: true
              productObj:
                type: object
                required: true
            example:
              userId: "g53a0000-8669-4a07-a23a-d18055600000"
              productObj:
                {
                  ProductId: "Product1",
                  ProductName: "Gạo tẻ",
                  Dates:
                    {
                      Cultivated: "",
                      Harvested: "",
                      Imported: "",
                      Manufacturered: "",
                      Exported: "",
                      Distributed: "",
                      Sold: ""
                    },
                  Actors:
                    {
                      SupplierId: "",
                      ManufacturerId: "",
                      DistributorId: "",
                      RetailerId: ""
                    },
                  Price: "100000",
                  Status: "",
                  Description: "Gạo tẻ đạt chuẩn"
                }
    responses:
      200:
        description: Successfully
      400:
        description: Failed
