/product/all:
  get:
    summary: Get All Products
    description: Get All Products
    parameters:
      - in: query
        name: userId
        schema:
          type: string
    tags:
      - Product
    responses:
      200:
        description: Successfully
      400:
        description: Failed

/product/detail:
  get:
    summary: Get Product
    description: Get Product
    parameters:
      - in: query
        name: userId
        schema:
          type: string
      - in: query
        name: productId
        schema:
          type: string
    tags:
      - Product
    responses:
      200:
        description: Successfully
      400:
        description: Failed

/product/transactions-history:
  get:
    summary: Get Product Transactions History
    description: Get Product Transactions History
    parameters:
      - in: query
        name: userId
        schema:
          type: string
      - in: query
        name: productId
        schema:
          type: string
    tags:
      - Product
    responses:
      200:
        description: Successfully
      400:
        description: Failed

/product/cultivate:
  post:
    summary: Cultivate Product
    description: Cultivate Product
    tags:
      - Product
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              userId:
                type: string
                required: true
              productObj:
                type: object
                required: true
            example:
              userId: "g53a0000-8669-4a07-a23a-d18055600000"
              productObj:
                {
                  productId: "Product1",
                  productName: "Gạo tẻ",
                  dates:
                    {
                      cultivated: "",
                      harvested: "",
                      imported: "",
                      manufacturered: "",
                      exported: "",
                      distributed: "",
                      sold: ""
                    },
                  actors:
                    {
                      supplierId: "",
                      manufacturerId: "",
                      distributorId: "",
                      retailerId: ""
                    },
                  price: "100000",
                  status: "",
                  description: "Gạo tẻ đạt chuẩn",
                  certificateUrl: "http://localhost:4000/",
                  cooperationId: "g53a0000-8669-4a07-a23a-d18055601111",
                  image: ["http://localhost:4000/", "http://localhost:4001/"]
                }
    responses:
      200:
        description: Successfully
      400:
        description: Failed

/product/harvert:
  post:
    summary: Harvert Product
    description: Harvert Product
    tags:
      - Product
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              userId:
                type: string
                required: true
              productObj:
                type: object
                required: true
            example:
              userId: "g53a0000-8669-4a07-a23a-d18055600000"
              productObj:
                {
                  productId: "Product1",
                  productName: "Gạo tẻ",
                  dates:
                    {
                      cultivated: "",
                      harvested: "",
                      imported: "",
                      manufacturered: "",
                      exported: "",
                      distributed: "",
                      sold: ""
                    },
                  actors:
                    {
                      supplierId: "",
                      manufacturerId: "",
                      distributorId: "",
                      retailerId: ""
                    },
                  price: "100000",
                  status: "",
                  description: "Gạo tẻ đạt chuẩn",
                  certificateUrl: "http://localhost:4000/",
                  cooperationId: "g53a0000-8669-4a07-a23a-d18055601111",
                  image: ["http://localhost:4000/", "http://localhost:4001/"]
                }
    responses:
      200:
        description: Successfully
      400:
        description: Failed

/product/import:
  post:
    summary: Import Product
    description: Import Product
    tags:
      - Product
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              userId:
                type: string
                required: true
              productObj:
                type: object
                required: true
            example:
              userId: "g53a0000-8669-4a07-a23a-d18055600000"
              productObj:
                {
                  productId: "Product1",
                  productName: "Gạo tẻ",
                  dates:
                    {
                      cultivated: "",
                      harvested: "",
                      imported: "",
                      manufacturered: "",
                      exported: "",
                      distributed: "",
                      sold: ""
                    },
                  actors:
                    {
                      supplierId: "",
                      manufacturerId: "",
                      distributorId: "",
                      retailerId: ""
                    },
                  price: "100000",
                  status: "",
                  description: "Gạo tẻ đạt chuẩn",
                  certificateUrl: "http://localhost:4000/",
                  cooperationId: "g53a0000-8669-4a07-a23a-d18055601111",
                  image: ["http://localhost:4000/", "http://localhost:4001/"]
                }
    responses:
      200:
        description: Successfully
      400:
        description: Failed

/product/manufacture:
  post:
    summary: Manufacture Product
    description: Manufacture Product
    tags:
      - Product
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              userId:
                type: string
                required: true
              productObj:
                type: object
                required: true
            example:
              userId: "g53a0000-8669-4a07-a23a-d18055600000"
              productObj:
                {
                  productId: "Product1",
                  productName: "Gạo tẻ",
                  dates:
                    {
                      cultivated: "",
                      harvested: "",
                      imported: "",
                      manufacturered: "",
                      exported: "",
                      distributed: "",
                      sold: ""
                    },
                  actors:
                    {
                      supplierId: "",
                      manufacturerId: "",
                      distributorId: "",
                      retailerId: ""
                    },
                  price: "100000",
                  status: "",
                  description: "Gạo tẻ đạt chuẩn",
                  certificateUrl: "http://localhost:4000/",
                  cooperationId: "g53a0000-8669-4a07-a23a-d18055601111",
                  image: ["http://localhost:4000/", "http://localhost:4001/"]
                }
    responses:
      200:
        description: Successfully
      400:
        description: Failed

/product/export:
  post:
    summary: Export Product
    description: Export Product
    tags:
      - Product
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              userId:
                type: string
                required: true
              productObj:
                type: object
                required: true
            example:
              userId: "g53a0000-8669-4a07-a23a-d18055600000"
              productObj:
                {
                  productId: "Product1",
                  productName: "Gạo tẻ",
                  dates:
                    {
                      cultivated: "",
                      harvested: "",
                      imported: "",
                      manufacturered: "",
                      exported: "",
                      distributed: "",
                      sold: ""
                    },
                  actors:
                    {
                      supplierId: "",
                      manufacturerId: "",
                      distributorId: "",
                      retailerId: ""
                    },
                  price: "100000",
                  status: "",
                  description: "Gạo tẻ đạt chuẩn",
                  certificateUrl: "http://localhost:4000/",
                  cooperationId: "g53a0000-8669-4a07-a23a-d18055601111",
                  image: ["http://localhost:4000/", "http://localhost:4001/"]
                }
    responses:
      200:
        description: Successfully
      400:
        description: Failed

/product/distribute:
  post:
    summary: Distribute Product
    description: Distribute Product
    tags:
      - Product
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              userId:
                type: string
                required: true
              productObj:
                type: object
                required: true
            example:
              userId: "g53a0000-8669-4a07-a23a-d18055600000"
              productObj:
                {
                  productId: "Product1",
                  productName: "Gạo tẻ",
                  dates:
                    {
                      cultivated: "",
                      harvested: "",
                      imported: "",
                      manufacturered: "",
                      exported: "",
                      distributed: "",
                      sold: ""
                    },
                  actors:
                    {
                      supplierId: "",
                      manufacturerId: "",
                      distributorId: "",
                      retailerId: ""
                    },
                  price: "100000",
                  status: "",
                  description: "Gạo tẻ đạt chuẩn",
                  certificateUrl: "http://localhost:4000/",
                  cooperationId: "g53a0000-8669-4a07-a23a-d18055601111",
                  image: ["http://localhost:4000/", "http://localhost:4001/"]
                }
    responses:
      200:
        description: Successfully
      400:
        description: Failed

/product/sell:
  post:
    summary: Sell Product
    description: Sell Product
    tags:
      - Product
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              userId:
                type: string
                required: true
              productObj:
                type: object
                required: true
            example:
              userId: "g53a0000-8669-4a07-a23a-d18055600000"
              productObj:
                {
                  productId: "Product1",
                  productName: "Gạo tẻ",
                  dates:
                    {
                      cultivated: "",
                      harvested: "",
                      imported: "",
                      manufacturered: "",
                      exported: "",
                      distributed: "",
                      sold: ""
                    },
                  actors:
                    {
                      supplierId: "",
                      manufacturerId: "",
                      distributorId: "",
                      retailerId: ""
                    },
                  price: "100000",
                  status: "",
                  description: "Gạo tẻ đạt chuẩn",
                  certificateUrl: "http://localhost:4000/",
                  cooperationId: "g53a0000-8669-4a07-a23a-d18055601111",
                  image: ["http://localhost:4000/", "http://localhost:4001/"]
                }
    responses:
      200:
        description: Successfully
      400:
        description: Failed

/product/update:
  patch:
    summary: Update Product
    description: Update Product
    tags:
      - Product
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              userId:
                type: string
                required: true
              productObj:
                type: object
                required: true
            example:
              userId: "g53a0000-8669-4a07-a23a-d18055600000"
              productObj:
                {
                  productId: "Product1",
                  productName: "Gạo tẻ",
                  dates:
                    {
                      cultivated: "",
                      harvested: "",
                      imported: "",
                      manufacturered: "",
                      exported: "",
                      distributed: "",
                      sold: ""
                    },
                  actors:
                    {
                      supplierId: "",
                      manufacturerId: "",
                      distributorId: "",
                      retailerId: ""
                    },
                  price: "100000",
                  status: "",
                  description: "Gạo tẻ đạt chuẩn",
                  certificateUrl: "http://localhost:4000/",
                  cooperationId: "g53a0000-8669-4a07-a23a-d18055601111",
                  image: ["http://localhost:4000/", "http://localhost:4001/"]
                }
    responses:
      200:
        description: Successfully
      400:
        description: Failed
