/product/transaction-history/{productId}:
  get:
    summary: Get Product Transaction History
    description: Get Product Transaction History
    parameters:
      - in: path
        name: productId
        schema:
          type: string
    tags:
      - Product
    responses:
      200:
        description: Successfully
      400:
        description: Failed
      404:
        description: Not Found

/product/all:
  get:
    summary: Get All Products
    description: Get All Products
    tags:
      - Product
    responses:
      200:
        description: Successfully
      400:
        description: Failed
      404:
        description: Not Found

/product/{productId}:
  get:
    summary: Get Detail Product
    description: Get Detail Product
    parameters:
      - in: path
        name: productId
        schema:
          type: string
    tags:
      - Product
    responses:
      200:
        description: Successfully
      400:
        description: Failed
      404:
        description: Not Found

/product/transactions-history:
  get:
    summary: Get Product Transactions History
    description: Get Product Transactions History
    parameters:
      - in: query
        name: productId
        schema:
          type: string
    tags:
      - Product
    responses:
      200:
        description: Successfully
      400:
        description: Failed
      404:
        description: Not Found

/product/cultivate:
  post:
    summary: Cultivate Product
    description: Cultivate Product
    tags:
      - Product
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              productObj:
                type: object
                required: true
            example:
              productObj:
                {
                  productName: "Gạo tẻ",
                  price: "100000",
                  amount: "1",
                  unit: "kg",
                  description: "Gạo tẻ đạt chuẩn",
                  certificateUrl: "http://localhost:4000/image1.img",
                  image:
                    [
                      "http://localhost:4000/image1.img",
                      "http://localhost:4000/image2.img"
                    ]
                }
    responses:
      200:
        description: Successfully
      400:
        description: Failed
      404:
        description: Not Found

/product/harvest:
  post:
    summary: Harvest Product
    description: Harvest Product
    tags:
      - Product
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              productId:
                type: string
                required: true
            example:
              productId: "Product1"
    responses:
      200:
        description: Successfully
      400:
        description: Failed
      404:
        description: Not Found

/product/import:
  post:
    summary: Import Product
    description: Import Product
    tags:
      - Product
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              productId:
                type: string
                required: true
              price:
                type: string
                required: true
            example:
              productId: "Product1"
              price: "100000"
    responses:
      200:
        description: Successfully
      400:
        description: Failed
      404:
        description: Not Found

/product/manufacture:
  post:
    summary: Manufacture Product
    description: Manufacture Product
    tags:
      - Product
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              productId:
                type: string
                required: true
              imageUrl:
                type: array
                required: true
              expireTime:
                type: string
                required: true
            example:
              productId: "Product1"
              imageUrl:
                [
                  "http://localhost:4000/image1.img",
                  "http://localhost:4000/image2.img"
                ]
              expireTime: "2023-06-03 09:37:48.94 +0000 UTC"
    responses:
      200:
        description: Successfully
      400:
        description: Failed
      404:
        description: Not Found

/product/update:
  patch:
    summary: Update Product
    description: Update Product
    tags:
      - Product
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              productObj:
                type: object
                required: true
            example:
              productObj:
                {
                  productName: "Gạo tẻ",
                  price: "100000",
                  amount: "1",
                  unit: "kg",
                  description: "Gạo tẻ đạt chuẩn",
                  certificateUrl: "http://localhost:4000/image1.img",
                  image:
                    [
                      "http://localhost:4000/image1.img",
                      "http://localhost:4000/image2.img"
                    ]
                }
    responses:
      200:
        description: Successfully
      400:
        description: Failed
      404:
        description: Not Found
