### sign up
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "phoneNumber": "+84708548819",
  "password": "Ryn"
}


### verify
POST  http://localhost:4000/auth/verify
Content-Type: application/json

{
    "phoneNumber": "+84886755772",
    "otp": "861030"
}

### upload
POST http://localhost:4000/image/upload
Content-Type: application/json

{
  "imageString": "https://firebasestorage.googleapis.com/v0/b/supply-chain-9ea64.appspot.com/o/Images%20product%2FMật%20ong%2F1684723468253.jpg?alt=media&token=d8acdd79-7473-4971-b68f-06f61549126b",
  "imagePathNameToFirebase": "tezt/tezt.jpg"
}